from __future__ import annotations

SERVER_COLUMNS = [
    "id",
    "name",
    "host",
    "api_url",
    "username",
    "password",
    "inbound_id",
    "public_key",
    "short_id",
    "country",
    "is_active",
    "sni",
    "public_port",
    "ws_path",
    "ws_host",
    "last_health_check",
    "health_errors",
    "last_error",
    "max_users",
    "server_role",
    "upstream_id",
    "gateway_apply_status",
    "gateway_apply_error",
    "gateway_applied_at",
    "gateway_config_path",
    "gateway_service_name",
]

EXTERNAL_UPSTREAM_COLUMNS = [
    "id",
    "name",
    "raw_json",
    "config_hash",
    "is_active",
    "source_kind",
    "source_path",
    "default_route_mode",
    "validation_status",
    "validation_error",
    "last_applied_at",
    "created_at",
    "updated_at",
]
